---
- name: deploy
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Deploy flask app
      condition: event.payload.message == "deploy"
      action:
        run_job_template:
          name: flaskapp-deploy
          organization: "Default"
